/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as campaignSol from "./Campaign.sol";
export type { campaignSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { CampaignFactory } from "./CampaignFactory";
